port: 7890
socks-port: 7891


mode: rule
ipv6: false

proxies:
  - name: "shadowsocks"
    type: ss
    server: <SERVER-IP>
    port: 8088
    cipher: aes-256-cfb
    password: <PASSWORD>
    plugin: obfs
    plugin-opts:
      mode: http

proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - shadowsocks

rules:
  - GEOIP,IR,DIRECT
  - DOMAIN-SUFFIX,ir,DIRECT
  - MATCH,Proxy
